services:
  bot:
    image: leaftail/save-from-e621-tg-bot
    environment:
      # Telegram bot token
      - TOKEN=1111:xxxxxx

      # Optional 
      # Telegram bot webhook url. Leave empty to use long polling
      # - WEBHOOK_URL=

      # If provided, limits interaction with bot to this user
      # - USER_ID=

      # Whenether to warn other users or just ignore their messages. Respected only when USER_ID is provided
      # - WARN_OTHER_USERS=true

      # If e621 is blocked, uses this url as proxy
      # - E621_PROXY=

      # Interval to check for e621 availability status in hours. Set 0 to disable
      # - E621_CHECK_INTERVAL_HOURS=

      - DOCKER=true

      # Where to save images to
      - SAVE_TO_PATH=/usr/bot/images/

    volumes:
      - ./docker-images:/usr/bot/images/